<?php

use Illuminate\Database\Seeder;
use App\Models\Color;
use App\Models\ColorGroup;
class ColorTealGreenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            [
                'name' =>  "Silky Ice",
                'color' =>  "#E7F1EC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 83/034",
                'color' =>  "#E2ECE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 83/053",
                'color' =>  "#DEECEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Polar Landscape",
                'color' =>  "#DEEBE8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Water Sensation",
                'color' =>  "#DEEBE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 83/057",
                'color' =>  "#DDEDEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gentle Clarity",
                'color' =>  "#DDEDEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 83/061",
                'color' =>  "#DCEDEC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Diamond Blue",
                'color' =>  "#DCEDEC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GG 83/075",
                'color' =>  "#DBEEE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 83/069",
                'color' =>  "#D9EDEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Alpine Air",
                'color' =>  "#D9EDEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Greenish Glow",
                'color' =>  "#D8E8E3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Arctic Atmosphere",
                'color' =>  "#D8E7E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Iconic Iceberg",
                'color' =>  "#D7EBE3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Elderflower Hint",
                'color' =>  "#D6EAE2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Exciting Summer",
                'color' =>  "#D6E8E8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50BG 76/068",
                'color' =>  "#D2E4E8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "78GG 79/109",
                'color' =>  "#CBEBE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cool Dip",
                'color' =>  "#CBEBE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Regent Street",
                'color' =>  "#CAE3DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 75/092",
                'color' =>  "#CAE3DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Reflected Sky",
                'color' =>  "#CADEE1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 72/069",
                'color' =>  "#C9DDDD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winterscape",
                'color' =>  "#C8E6E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 76/107",
                'color' =>  "#C8E6E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 74/092",
                'color' =>  "#C8E2DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lagoon Green",
                'color' =>  "#C8E2DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Summer Showers",
                'color' =>  "#C6E1E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 72/092",
                'color' =>  "#C6E1E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Warm Breeze",
                'color' =>  "#C4E1E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 72/103",
                'color' =>  "#C4E1E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Aqua Tint",
                'color' =>  "#C3E3DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 74/108",
                'color' =>  "#C3E3DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sublime Ocean",
                'color' =>  "#C1E6E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56GG 77/156",
                'color' =>  "#BEE9DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Ibiza Blues",
                'color' =>  "#BEE2E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gercian Sea",
                'color' =>  "#BEE1E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Toy Green",
                'color' =>  "#BDE8DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Relaxing Bath",
                'color' =>  "#BAE3DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sky High Blue",
                'color' =>  "#B9E3E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "13BG 72/151",
                'color' =>  "#B9E3E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lime Foam",
                'color' =>  "#B9DED3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 69/134",
                'color' =>  "#B9DED3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 64/140",
                'color' =>  "#B3D7DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Bella Sky",
                'color' =>  "#B3D6DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Ocean Spray",
                'color' =>  "#B2E5D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 71/180",
                'color' =>  "#B2E5D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Notorious Green",
                'color' =>  "#B1DCCF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 66/157",
                'color' =>  "#AEDCD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 63/143",
                'color' =>  "#ACD6D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lake Blue",
                'color' =>  "#ACD6D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 61/154",
                'color' =>  "#AAD4C8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sunny Green",
                'color' =>  "#AAD4C8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Caribbean Medley",
                'color' =>  "#A8DEE2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Magnificent Mint",
                'color' =>  "#A1D8D4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Windy Hill",
                'color' =>  "#9FD8DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 63/189",
                'color' =>  "#9FD8DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Shoreline",
                'color' =>  "#96D6DD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "19BG 61/207",
                'color' =>  "#96D6DD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "89GG 63/216",
                'color' =>  "#95D9D5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56GG 64/258",
                'color' =>  "#90DDCD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fruity Melon",
                'color' =>  "#8ED3C2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Aqua Memories",
                'color' =>  "#8CD5DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "87GG 60/239",
                'color' =>  "#8BD6D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 60/251",
                'color' =>  "#8BD6CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Floating Bubbles",
                'color' =>  "#8BD6CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Flourish Green",
                'color' =>  "#89D6D5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 55/223",
                'color' =>  "#89CED2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Moonglow",
                'color' =>  "#89CED2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Bermuda Pool",
                'color' =>  "#88C8C6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 51/211",
                'color' =>  "#88C8C6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 43/213",
                'color' =>  "#7CB8AA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wave Garden",
                'color' =>  "#78BEB1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 39/219",
                'color' =>  "#6AB1B6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Barondale Blue",
                'color' =>  "#6AB1B6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 50/320",
                'color' =>  "#69CAB7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "87GG 51/291",
                'color' =>  "#68CAC5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Vista Marine",
                'color' =>  "#63B3B9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 39/244",
                'color' =>  "#63B3B9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "18BG 47/282",
                'color' =>  "#61C3CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Emerald Sensation",
                'color' =>  "#57B5A2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Neptune's Jewel",
                'color' =>  "#55B7AC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 39/303",
                'color' =>  "#55B7AC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Opal Treasure",
                'color' =>  "#53BFCB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "53GG 50/360",
                'color' =>  "#50C7B3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Thai Teal",
                'color' =>  "#50C7B3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 28/273",
                'color' =>  "#4B9C8C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Future Green",
                'color' =>  "#4B9C8C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 33/269",
                'color' =>  "#49A7B5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Big Sea",
                'color' =>  "#49A7B5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Motion Blue",
                'color' =>  "#44BFBE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 41/379",
                'color' =>  "#42BEA7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 27/273",
                'color' =>  "#3D9A99",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "21229",
                'color' =>  "#308E89",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Parsley Scene",
                'color' =>  "#2F7769",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 18/261",
                'color' =>  "#2D8071",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "17BG 36/333",
                'color' =>  "#20ADB8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Taking The Plunge",
                'color' =>  "#20ADB8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 09/189",
                'color' =>  "#1F564C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Emerald City",
                'color' =>  "#1F564C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 22/275",
                'color' =>  "#1C8C93",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "50GG 11/251",
                'color' =>  "#0D6456",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Caribbean Pleasure",
                'color' =>  "#00AA8F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "46GG 31/446",
                'color' =>  "#00AA8F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "50GG 30/467",
                'color' =>  "#00A58D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Marine Blue",
                'color' =>  "#00A4A6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "88GG 32/346",
                'color' =>  "#00A4A6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "16BG 29/350",
                'color' =>  "#00A1AD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Light Parade",
                'color' =>  "#009E82",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "80GG 27/386",
                'color' =>  "#009C97",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Dramatic Sea",
                'color' =>  "#009B96",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "44GG 24/451",
                'color' =>  "#00997E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Marine Miracle",
                'color' =>  "#0098A4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Electric Asure",
                'color' =>  "#0096A2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "16BG 24/357",
                'color' =>  "#00939F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Deep Pool",
                'color' =>  "#008C86",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "78GG 21/381",
                'color' =>  "#008C86",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "30BG 21/301",
                'color' =>  "#008897",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Cosmic Blue",
                'color' =>  "#008897",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Caribbean Delight",
                'color' =>  "#00879E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 18/353",
                'color' =>  "#008571",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Flawless Moment",
                'color' =>  "#00837D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Seaweed Sensation",
                'color' =>  "#00836E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 16/390",
                'color' =>  "#007F74",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Subtle Snake",
                'color' =>  "#007F6E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 15/398",
                'color' =>  "#007A7A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Christmas Spruce",
                'color' =>  "#007A7A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Venetian Turquoise",
                'color' =>  "#007585",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 15/322",
                'color' =>  "#007585",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "10BG 14/296",
                'color' =>  "#00737A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70GG 13/323",
                'color' =>  "#007067",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Zodiac Night",
                'color' =>  "#007067",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Zodiac Night",
                'color' =>  "#007067",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Happy Bush",
                'color' =>  "#006755",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GY 83/021",
                'color' =>  "#EBEAE4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Extreme White",
                'color' =>  "#EBEAE4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pale Diamond",
                'color' =>  "#E7EAE4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 83/023",
                'color' =>  "#E5E9E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Icy Pond",
                'color' =>  "#E5E9E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 83/023",
                'color' =>  "#E4EBE7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lofty Dream",
                'color' =>  "#E4EBE7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 83/018",
                'color' =>  "#E4EAE7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 83/034",
                'color' =>  "#E3ECE7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Goodnite Moon",
                'color' =>  "#E0E6E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45GG 81/022",
                'color' =>  "#E0E6E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Iced Earth",
                'color' =>  "#D7E3E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "04BG 74/037",
                'color' =>  "#D5E0DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Light Opal",
                'color' =>  "#D5DDD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 73/031",
                'color' =>  "#D5DDD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "95GG 78/054",
                'color' =>  "#D4E4E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mellow Turtle",
                'color' =>  "#D2E6E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56GG 75/052",
                'color' =>  "#D2E1DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tracery",
                'color' =>  "#D1DEDF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 72/051",
                'color' =>  "#D1DEDF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 72/045",
                'color' =>  "#D1DDD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Autumn Mist",
                'color' =>  "#D1DDD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gentle Green",
                'color' =>  "#CFEDE3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 82/115",
                'color' =>  "#CFEDE3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 72/057",
                'color' =>  "#CEDFDD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Vienna Lake",
                'color' =>  "#CEDFDD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 73/062",
                'color' =>  "#CDDFDB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Metallic Sheen",
                'color' =>  "#CBD5D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "21208",
                'color' =>  "#CADFD7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 63/042",
                'color' =>  "#C6D1CD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grey Leaf",
                'color' =>  "#C6D1CD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "73479",
                'color' =>  "#C2CECB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 63/062",
                'color' =>  "#C1D2CF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gentle Flow",
                'color' =>  "#BDD9D6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 64/072",
                'color' =>  "#BDD1D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Clear Sailing",
                'color' =>  "#BDD1D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Rainy Sensation",
                'color' =>  "#BCCCC9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 64/088",
                'color' =>  "#B9D3D1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 55/049",
                'color' =>  "#B8C6C2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 63/097",
                'color' =>  "#B5D3D2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Skywatch",
                'color' =>  "#B5D3D2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Falling Rain",
                'color' =>  "#ADC9CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 56/097",
                'color' =>  "#ADC9CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Heavy Air",
                'color' =>  "#A9C4BF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 57/146",
                'color' =>  "#A1CCCA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 57/149",
                'color' =>  "#A0CCD3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Froggy Style",
                'color' =>  "#A0C6C2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Bear Run",
                'color' =>  "#98B9BB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 46/112",
                'color' =>  "#98B9BB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 40/064",
                'color' =>  "#98A9A4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gravel Pit",
                'color' =>  "#98A9A4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gravel Pit",
                'color' =>  "#98A9A4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 54/199",
                'color' =>  "#90CCD0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Turtle Garden",
                'color' =>  "#90B9B5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 39/088",
                'color' =>  "#90A8A4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Hillside View",
                'color' =>  "#90A8A4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Forest Glen",
                'color' =>  "#8CADAC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 40/115",
                'color' =>  "#8CADAC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 43/163",
                'color' =>  "#88B7BF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Blue Niche",
                'color' =>  "#88B7BF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Jasperware",
                'color' =>  "#88ABAD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 38/119",
                'color' =>  "#88ABAD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Seacliff",
                'color' =>  "#85A6AB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 37/110",
                'color' =>  "#85A6AB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lagoon Rest",
                'color' =>  "#83C5CE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 42/171",
                'color' =>  "#81B5B4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Thunder Sensation",
                'color' =>  "#76908D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 27/105",
                'color' =>  "#73908B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Crystal Sensation",
                'color' =>  "#6DB0AC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 23/085",
                'color' =>  "#6D837D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Midnight Garden",
                'color' =>  "#6D837D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Still Waters",
                'color' =>  "#6C9393",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 28/133",
                'color' =>  "#6C9393",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Caribean Sea",
                'color' =>  "#6BB7C4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 44/248",
                'color' =>  "#69B9C5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Goose Bay",
                'color' =>  "#699093",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 26/134",
                'color' =>  "#699093",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 38/242",
                'color' =>  "#64B1AF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Riverboat Cruise",
                'color' =>  "#62A3AD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 33/207",
                'color' =>  "#62A3AD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Smoked Turquoise",
                'color' =>  "#62868B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 23/124",
                'color' =>  "#62868B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cheeky Grey",
                'color' =>  "#627775",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 30/195",
                'color' =>  "#609C9B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Seven Lakes",
                'color' =>  "#609C9B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fall's River",
                'color' =>  "#5A8487",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 21/141",
                'color' =>  "#5A8487",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70GG 18/122",
                'color' =>  "#567773",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "50GG 15/099",
                'color' =>  "#536B66",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Brooding Blue",
                'color' =>  "#4E6C69",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 19/151",
                'color' =>  "#4D7A79",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Serene Moments",
                'color' =>  "#4B7B78",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 16/133",
                'color' =>  "#4B7278",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Berkeley Blue",
                'color' =>  "#4B7278",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Artichoke Swing",
                'color' =>  "#48877D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 21/219",
                'color' =>  "#3F8685",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70GG 11/140",
                'color' =>  "#3B605C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "30BG 10/111",
                'color' =>  "#39595F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Bohemian Blue",
                'color' =>  "#39595F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cape Storm",
                'color' =>  "#386A6D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 13/156",
                'color' =>  "#386A6D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Waterfall Wall",
                'color' =>  "#37919D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 11/131",
                'color' =>  "#365E5E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10BG 22/248",
                'color' =>  "#308A91",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "90GG 08/118",
                'color' =>  "#2C4F4F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Peacock Fan",
                'color' =>  "#2A7C79",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 12/206",
                'color' =>  "#246969",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Seaweed Medley",
                'color' =>  "#22625F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 08/143",
                'color' =>  "#1E4F56",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Deepest Cyan",
                'color' =>  "#154946",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dark Bush",
                'color' =>  "#10514E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Persian Dreams",
                'color' =>  "#0F4C4B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Artisan",
                'color' =>  "#006E7B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 14/248",
                'color' =>  "#006E7B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Intense Caribbean",
                'color' =>  "#006872",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 11/295",
                'color' =>  "#006867",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Blue Freedom",
                'color' =>  "#006663",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 11/278",
                'color' =>  "#00656B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Turbulent Tropics",
                'color' =>  "#005E63",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "26BG 09/247",
                'color' =>  "#005D67",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Mountain Majesty",
                'color' =>  "#005D56",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70GG 09/223",
                'color' =>  "#005D56",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10BG 10/222",
                'color' =>  "#005B61",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Intense Depths",
                'color' =>  "#005765",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 08/200",
                'color' =>  "#00565F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Narragansett",
                'color' =>  "#00565F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lush Seaweed",
                'color' =>  "#004C52",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Energizing Emerald",
                'color' =>  "#004641",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BG 83/053",
                'color' =>  "#DEECEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 63/042",
                'color' =>  "#C6D1CD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56GG 77/156",
                'color' =>  "#BEE9DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BG 64/072",
                'color' =>  "#BDD1D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "73501",
                'color' =>  "#B3D3BE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "87GG 51/291",
                'color' =>  "#68CAC5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
        ];

        $colorGrp = ColorGroup::where('name', 'Họ màu xanh mòng két')->first();
        if ($colorGrp) {
            foreach($colors as $cl) {
                $color = Color::create([
                    'name' => $cl['name'],
                    'color' => $cl['color'],
                    'mixed_by_computer' => $cl['mixed_by_computer'],
                    'is_deep_color' => $cl['is_deep_color'],
                    'is_popular' => $cl['is_popular'],
                    'color_group_id' => $colorGrp->id
                ]);
                if ($color) {
                    $color->surfaces()->sync($cl['surfaces']);
                    $color->projecttypes()->sync($cl['projectTypes']);
                }
            }
        }
    }
}
