<?php

use Illuminate\Database\Seeder;
use App\Models\Color;
use App\Models\ColorGroup;
class ColorYellowSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            [
                'name' =>  "50YY 80/455",
                'color' =>  "#FFE087",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 79/376",
                'color' =>  "#FFDF96",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "48YY 77/529",
                'color' =>  "#FFDD78",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sunny",
                'color' =>  "#FFDC8C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 77/424",
                'color' =>  "#FFDC8C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Starlight Burst",
                'color' =>  "#FFD967",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 73/519",
                'color' =>  "#FFD571",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Yellow Rose",
                'color' =>  "#FFD571",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "46YY 74/602",
                'color' =>  "#FFD562",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 71/664",
                'color' =>  "#FFD145",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Buttercup Bliss",
                'color' =>  "#FFD04A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 69/614",
                'color' =>  "#FFCF57",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "41YY 69/742",
                'color' =>  "#FFCE38",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "39YY 66/628",
                'color' =>  "#FFCB4D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "40YY 64/903",
                'color' =>  "#FFC700",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Blazing Star",
                'color' =>  "#FFC700",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "39YY 66/813",
                'color' =>  "#FFC600",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "37YY 61/877",
                'color' =>  "#FFC100",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "37YY 61/867",
                'color' =>  "#FFC100",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Omega Yellow",
                'color' =>  "#FFC100",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Summer Drift",
                'color' =>  "#FEE39F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sunrise Lift",
                'color' =>  "#FEE089",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Star Delight",
                'color' =>  "#FED56A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 71/567",
                'color' =>  "#FED362",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "53YY 83/348",
                'color' =>  "#FDE39F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Rainbow Yellow",
                'color' =>  "#FDD84F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Astral Light",
                'color' =>  "#FCE99C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 83/250",
                'color' =>  "#FCE5B4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sweet Buttercup",
                'color' =>  "#FCE5B4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lemon Lady",
                'color' =>  "#FCE462",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 67/662",
                'color' =>  "#FCCD46",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Camera Flash",
                'color' =>  "#FBEDBA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56YY 86/241",
                'color' =>  "#FBE8B8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "54YY 85/291",
                'color' =>  "#FBE5AD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Celestial Sun",
                'color' =>  "#FBE5AD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Burnt Lemon",
                'color' =>  "#FBCB3B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "39YY 68/634",
                'color' =>  "#FBC94A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "45YY 74/383",
                'color' =>  "#FAD98E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 65/710",
                'color' =>  "#FACA35",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Festival Yellow",
                'color' =>  "#FACA35",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 64/787",
                'color' =>  "#FACA22",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Gorgeous Lemon",
                'color' =>  "#F9E8BC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sublime Solar",
                'color' =>  "#F9C13B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Moon Fantasy",
                'color' =>  "#F8EFD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "67YY 87/169",
                'color' =>  "#F8EECC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/250",
                'color' =>  "#F8E6B5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Flaxseed",
                'color' =>  "#F8E1B2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 80/242",
                'color' =>  "#F8E1B2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "54YY 69/747",
                'color' =>  "#F8D02E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "May Tulip",
                'color' =>  "#F8CD6A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "43YY 69/543",
                'color' =>  "#F8CD6A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lemon Pepper",
                'color' =>  "#F8C62E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "42YY 64/745",
                'color' =>  "#F8C62E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "67YY 89/124",
                'color' =>  "#F7EED4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "North Star",
                'color' =>  "#F7EED4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "52YY 89/117",
                'color' =>  "#F7ECD5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "66YY 85/231",
                'color' =>  "#F7EBBD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Morning Feel",
                'color' =>  "#F7EAA5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Soft Yellow",
                'color' =>  "#F7E9C5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "58YY 88/180",
                'color' =>  "#F7E9C5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Coconut",
                'color' =>  "#F7E6CA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 83/150",
                'color' =>  "#F7E6CA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 79/367",
                'color' =>  "#F7DF96",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Yellow Fruitmix",
                'color' =>  "#F7DA99",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 62/805",
                'color' =>  "#F7C500",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Curry Spice",
                'color' =>  "#F7C500",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Moonscape",
                'color' =>  "#F6EDD1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "61YY 89/135",
                'color' =>  "#F6EDD1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Uplifting White",
                'color' =>  "#F6ECCC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/219",
                'color' =>  "#F6E6BB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Coastlight",
                'color' =>  "#F6E5C3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 83/171",
                'color' =>  "#F6E5C3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 83/200",
                'color' =>  "#F6E4BD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 80/288",
                'color' =>  "#F6E2A9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Chic Yellow",
                'color' =>  "#F6E2A9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 77/285",
                'color' =>  "#F6DDA6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Essential Yellow",
                'color' =>  "#F6CF6C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 66/512",
                'color' =>  "#F6CF6C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Morning Silk",
                'color' =>  "#F5EFD7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Spring Pear",
                'color' =>  "#F5EDCF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "75YY 87/137",
                'color' =>  "#F5EDCF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "76594",
                'color' =>  "#F5E2BB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 65/427",
                'color' =>  "#F5CB7B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cream Chic",
                'color' =>  "#F4ECD6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Summer Weekend",
                'color' =>  "#F4EAC6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 83/187",
                'color' =>  "#F4E9C2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/156",
                'color' =>  "#F4E7C8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Delicate Yellow",
                'color' =>  "#F4E6C0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/187",
                'color' =>  "#F4E6C0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 79/208",
                'color' =>  "#F4E0B8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 71/335",
                'color' =>  "#F4D497",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 68/381",
                'color' =>  "#F4D088",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Linwood Beach",
                'color' =>  "#F3EEDC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "71YY 87/078",
                'color' =>  "#F3EEDC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "35YY 86/117",
                'color' =>  "#F3E8D0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 77/332",
                'color' =>  "#F3DE9C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Southern Cross",
                'color' =>  "#F3DE9C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 75/216",
                'color' =>  "#F3DCB4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Orion",
                'color' =>  "#F3DCB4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 73/497",
                'color' =>  "#F3D975",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 71/369",
                'color' =>  "#F3D68E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 69/583",
                'color' =>  "#F3D15B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Electric Avenue",
                'color' =>  "#F3D15B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cream Sensation",
                'color' =>  "#F2E7CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lemon Sherbert",
                'color' =>  "#F2D486",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/125",
                'color' =>  "#F1E7CD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Yellow Kiwi",
                'color' =>  "#F1E4B8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 78/216",
                'color' =>  "#F0E2B7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "65YY 84/081",
                'color' =>  "#EFEAD6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Del Mar Shores",
                'color' =>  "#EFEAD6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Rich Yellow",
                'color' =>  "#EFD886",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 71/409",
                'color' =>  "#EFD886",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 65/454",
                'color' =>  "#EFD077",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Golden Bell",
                'color' =>  "#EFD077",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mustard Grass",
                'color' =>  "#EFC900",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 60/519",
                'color' =>  "#EFC25F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/094",
                'color' =>  "#EEE6D1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 67/626",
                'color' =>  "#EECF50",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Parakeet",
                'color' =>  "#EECD40",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 65/669",
                'color' =>  "#EECD40",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "40YY 63/473",
                'color' =>  "#EEC76E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Apple Touch",
                'color' =>  "#ECDB8B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 66/487",
                'color' =>  "#ECCE6C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 62/755",
                'color' =>  "#ECC722",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "50YY 60/538",
                'color' =>  "#EBC65D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Artifact",
                'color' =>  "#EBC65D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 58/565",
                'color' =>  "#EBBD51",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Swedish Green",
                'color' =>  "#EBBD51",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Bumble Fun",
                'color' =>  "#E7B523",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 59/604",
                'color' =>  "#E2C347",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "30YY 46/608",
                'color' =>  "#E2AC39",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "King's Ransom",
                'color' =>  "#E2AC39",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sulphur Burst",
                'color' =>  "#E0BA25",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Apple Valley",
                'color' =>  "#DFCD45",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "66YY 61/648",
                'color' =>  "#DFCD45",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Gold Curry",
                'color' =>  "#DEB349",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 49/546",
                'color' =>  "#DEB349",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "45YY 49/610",
                'color' =>  "#DDB338",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Indian Saffron",
                'color' =>  "#DBA000",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 41/700",
                'color' =>  "#DBA000",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "40YY 46/587",
                'color' =>  "#DAA937",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Tiara",
                'color' =>  "#DAA937",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Citrus Sunburst",
                'color' =>  "#D9C15B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Citrus Sunburst",
                'color' =>  "#D9C15B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 55/504",
                'color' =>  "#D9C15B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Rustic Drama",
                'color' =>  "#D9B500",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 48/748",
                'color' =>  "#D9B500",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Unripe Banana",
                'color' =>  "#D5BF19",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 51/669",
                'color' =>  "#D0BB2A",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Byzantine Gold",
                'color' =>  "#CEA127",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 41/603",
                'color' =>  "#CEA127",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Twist & Shout",
                'color' =>  "#CBB132",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 47/608",
                'color' =>  "#CBB132",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "40YY 38/643",
                'color' =>  "#CA9D08",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Forest Morning",
                'color' =>  "#C99C1D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 39/654",
                'color' =>  "#C4A91B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Shasta",
                'color' =>  "#C4A91B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 83/156",
                'color' =>  "#F8E8C9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cultured Pearl",
                'color' =>  "#F8E8C9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "May Yellow",
                'color' =>  "#F2DCAA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 75/254",
                'color' =>  "#F2DCAA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 78/140",
                'color' =>  "#F1E0C6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 77/183",
                'color' =>  "#F1DFBC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 83/112",
                'color' =>  "#F0E9D2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Boston Cream",
                'color' =>  "#F0E1BF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 77/173",
                'color' =>  "#F0E1BF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 83/075",
                'color' =>  "#EEE9D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 76/146",
                'color' =>  "#EEDEC1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 72/230",
                'color' =>  "#EED8AC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Musical Cream",
                'color' =>  "#EDDAB9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Innocent White",
                'color' =>  "#ECE9D9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Corn White",
                'color' =>  "#EBE4CC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 72/164",
                'color' =>  "#EAD9BA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Relaxing Light",
                'color' =>  "#E9DDC4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "City Morning",
                'color' =>  "#E8E1CB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 76/144",
                'color' =>  "#E8DEC0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Portuguese Sonnet",
                'color' =>  "#E8CC8D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 65/334",
                'color' =>  "#E8CC8D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 67/259",
                'color' =>  "#E7CF9E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 65/263",
                'color' =>  "#E7CC9B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 75/108",
                'color' =>  "#E6DEC8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 75/104",
                'color' =>  "#E6DCC6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dune Sensation",
                'color' =>  "#E6D9B7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Parchment",
                'color' =>  "#E6D7BD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 70/138",
                'color' =>  "#E6D7BD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Victorian Yellow",
                'color' =>  "#E6C780",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 61/368",
                'color' =>  "#E6C780",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wool White",
                'color' =>  "#E4DABF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 67/196",
                'color' =>  "#E4D0AB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sunshine Coast",
                'color' =>  "#E4D0AB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dazzling Desert",
                'color' =>  "#E3D5BB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Italian Green",
                'color' =>  "#E2CD9E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Morning Green",
                'color' =>  "#E2CB8F",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 64/165",
                'color' =>  "#DECCAE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Taupe Sheen",
                'color' =>  "#DBCAA4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Oriental Light",
                'color' =>  "#DBC399",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 51/519",
                'color' =>  "#DAB955",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Sapling",
                'color' =>  "#DAB955",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 67/117",
                'color' =>  "#D9D1B9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Triple Crown",
                'color' =>  "#D7B468",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "40YY 49/408",
                'color' =>  "#D7B468",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "60YY 57/304",
                'color' =>  "#D6C387",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Green Morning",
                'color' =>  "#D6BB82",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Scottish Green",
                'color' =>  "#D4B773",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tuscan Green",
                'color' =>  "#D1BE8E",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 53/218",
                'color' =>  "#D1BB93",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 46/304",
                'color' =>  "#CFAD78",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 47/236",
                'color' =>  "#CDB288",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Golden Rice",
                'color' =>  "#CDB288",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Golden Rice",
                'color' =>  "#CDB288",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 42/490",
                'color' =>  "#C6A747",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Pleasant Pear",
                'color' =>  "#C4AE73",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mustard Oil",
                'color' =>  "#C39E4B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fruit Fountain",
                'color' =>  "#BC9E36",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 39/225",
                'color' =>  "#BBA17B",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mustard Mud",
                'color' =>  "#B6A379",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Olive Fantasy",
                'color' =>  "#B68D2C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 35/249",
                'color' =>  "#B4986D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Old Salem Gold",
                'color' =>  "#B4986D",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 27/226",
                'color' =>  "#9F8662",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Khaki Moss",
                'color' =>  "#9F8662",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Green Seeweed",
                'color' =>  "#968550",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 23/246",
                'color' =>  "#967D54",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Dusty Countryside",
                'color' =>  "#967D54",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lakeside Town",
                'color' =>  "#938564",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Delicious Olive",
                'color' =>  "#937B3C",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 25/200",
                'color' =>  "#918762",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Tapenade Green",
                'color' =>  "#665936",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56YY 86/241",
                'color' =>  "#FBE8B8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "52YY 89/117",
                'color' =>  "#F7ECD5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/219",
                'color' =>  "#F6E6BB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 83/200",
                'color' =>  "#F6E4BD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "75YY 87/137",
                'color' =>  "#F5EDCF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "75271",
                'color' =>  "#F3E8D0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 65/454",
                'color' =>  "#EFD077",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 76/144",
                'color' =>  "#E8DEC0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "76924",
                'color' =>  "#E7E5D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
        ];

        $colorGrp = ColorGroup::where('name', 'Họ màu vàng')->first();
        if ($colorGrp) {
            foreach($colors as $cl) {
                $color = Color::create([
                    'name' => $cl['name'],
                    'color' => $cl['color'],
                    'mixed_by_computer' => $cl['mixed_by_computer'],
                    'is_deep_color' => $cl['is_deep_color'],
                    'is_popular' => $cl['is_popular'],
                    'color_group_id' => $colorGrp->id
                ]);
                if ($color) {
                    $color->surfaces()->sync($cl['surfaces']);
                    $color->projecttypes()->sync($cl['projectTypes']);
                }
            }
        }
    }
}
