<?php

use Illuminate\Database\Seeder;
use App\Models\Color;
use App\Models\ColorGroup;
class ColorVioletBlueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            [
                'name' =>  "Pink Sea Iris",
                'color' =>  "#EEE9EB",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "97RB 77/086",
                'color' =>  "#EEDBE5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Baby Pink",
                'color' =>  "#EEDBE5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lavender Lullaby",
                'color' =>  "#EDE8EA",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 83/017",
                'color' =>  "#ECE9EA",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Carnation",
                'color' =>  "#EBD3E2",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Magnificent Mauve",
                'color' =>  "#E6E2E6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Vesper Bell",
                'color' =>  "#E6DDE6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pinky",
                'color' =>  "#E6BDD9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Scent Of Lilac",
                'color' =>  "#E5DBE0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lyrical Poetry",
                'color' =>  "#E1D1DC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 74/038",
                'color' =>  "#E0DDE1",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Snow Lilac",
                'color' =>  "#E0DDE1",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pansy Touch",
                'color' =>  "#DDDAE4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Artistic Orchid",
                'color' =>  "#DDD2DF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Electric Pink",
                'color' =>  "#DDB1D4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Vesper",
                'color' =>  "#DCD1D9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pink Diamond",
                'color' =>  "#DCC5DD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "04RB 71/092",
                'color' =>  "#DBD8E7",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Heather Hills",
                'color' =>  "#D8D5E0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Clouds",
                'color' =>  "#D8D2E0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Evening Aperitif",
                'color' =>  "#D8D0D9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Violet Sensation",
                'color' =>  "#D6D9E7",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Vintage Violet",
                'color' =>  "#D6C8DE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tea Rose Garden",
                'color' =>  "#D6A4CC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Venitian Violet",
                'color' =>  "#D5BAD8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Touch Of Violet",
                'color' =>  "#D4D1DF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Smile",
                'color' =>  "#D4CFE3",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pink Tipple",
                'color' =>  "#D2B6CC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Foxglove",
                'color' =>  "#CDCCE1",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lavender Meadow",
                'color' =>  "#C9B9C9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pink Iris",
                'color' =>  "#C98EBD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lila Feel",
                'color' =>  "#C8CAE4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Viola",
                'color' =>  "#C8B7D6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lavender Sensation",
                'color' =>  "#C7C9D5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Carnival Mauve",
                'color' =>  "#C6C0D9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sensual Senses",
                'color' =>  "#C6B9CA",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 58/072",
                'color' =>  "#C5C6D2",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Smooth Grape",
                'color' =>  "#C3BACE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Amethyst Touch",
                'color' =>  "#BEC1D6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lilac Bouquet",
                'color' =>  "#BDBBDA",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 53/129",
                'color' =>  "#BCBED5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Precious Passion Fruit",
                'color' =>  "#BCB7D5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purpling",
                'color' =>  "#BCA5CC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mardi Gras",
                'color' =>  "#BC93C1",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Rosita",
                'color' =>  "#B973A8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Gorgeous Lilac",
                'color' =>  "#B8BCD4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dreamland",
                'color' =>  "#B897AF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dusk",
                'color' =>  "#AF98B0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Flowering Heather",
                'color' =>  "#AEB5D4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Precocious Purple",
                'color' =>  "#AEB0C8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dignity",
                'color' =>  "#AD94C2",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Mix",
                'color' =>  "#A79DC8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Vineyard Passage",
                'color' =>  "#A493AC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 34/153",
                'color' =>  "#A493AC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Regal Robe",
                'color' =>  "#A398B4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Illusion",
                'color' =>  "#A185B7",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fable",
                'color' =>  "#9E7594",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Elevator",
                'color' =>  "#9C98B6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lara's Theme",
                'color' =>  "#9A729C",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lavender Luxury",
                'color' =>  "#97A1CF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Princely Purple",
                'color' =>  "#9799B8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Passion",
                'color' =>  "#9477AC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Phenomenal Purple",
                'color' =>  "#9390BE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mellow Aubergine",
                'color' =>  "#8D84B5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 31/208",
                'color' =>  "#8B90B5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Vivid Lavender",
                'color' =>  "#8B81BA",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grape Surprise",
                'color' =>  "#867091",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Up Tempo",
                'color' =>  "#85689E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purfect Purple",
                'color' =>  "#848DB5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lilac Light",
                'color' =>  "#83769B",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lilac Splendor",
                'color' =>  "#8085AE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Concord Grape",
                'color' =>  "#7D6D99",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Stage Fright",
                'color' =>  "#7D5F7F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Boutique",
                'color' =>  "#7C4E75",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Regal Rebellion",
                'color' =>  "#7586C6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Fire",
                'color' =>  "#74568C",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Casa Royale",
                'color' =>  "#734D6C",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 14/232",
                'color' =>  "#725A7F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "90BB 21/220",
                'color' =>  "#71779E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Purple Wish",
                'color' =>  "#71779E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Amethyst Dream",
                'color' =>  "#6F68A4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Juicy Blueberry",
                'color' =>  "#6C7AAB",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Evening Drama",
                'color' =>  "#68709F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Spacious Lilac",
                'color' =>  "#677DAD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Boysenberry",
                'color' =>  "#655A7B",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grape Jamboree",
                'color' =>  "#63406E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Persian Palace",
                'color' =>  "#625894",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "California Raisin",
                'color' =>  "#624B6E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Inkberry",
                'color' =>  "#603960",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Seductive Mood",
                'color' =>  "#5F507A",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Plum Babe",
                'color' =>  "#5A638D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Very Vino",
                'color' =>  "#573B55",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Powerfull Plum",
                'color' =>  "#546894",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Proper Purple",
                'color' =>  "#523B64",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Royal Decree",
                'color' =>  "#4A5A88",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Twilight Zone",
                'color' =>  "#333D6B",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Thunder Night",
                'color' =>  "#324169",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RB 83/017",
                'color' =>  "#EBE8E9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Angel's Gaze",
                'color' =>  "#EBE8E9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Floral Twist",
                'color' =>  "#E7DDDE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RR 75/039",
                'color' =>  "#E7DDDE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Snow Season",
                'color' =>  "#E4E8EC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Phenomenal Plum",
                'color' =>  "#E4E5EA",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Galactic Mauve",
                'color' =>  "#E3DEE2",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Morning Dewdrops",
                'color' =>  "#E3DBDC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Heather Hint",
                'color' =>  "#E1DFE4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 74/033",
                'color' =>  "#E0DDE0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Castle In The Air",
                'color' =>  "#E0DDE0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RB 74/028",
                'color' =>  "#E0DBDE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mystic Purple",
                'color' =>  "#DFDDE2",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 74/038",
                'color' =>  "#DFDDE2",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lilac Dream",
                'color' =>  "#DFDBDD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 73/024",
                'color' =>  "#DFDBDD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Soothing Melody",
                'color' =>  "#DEDBDE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 73/027",
                'color' =>  "#DEDBDE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Diamond Dust",
                'color' =>  "#DDDBDC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 73/024",
                'color' =>  "#DDDBDC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Energetic Orchid",
                'color' =>  "#DAD2D8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RB 65/044",
                'color' =>  "#D5CFD4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Serene Summit",
                'color' =>  "#D5CFD4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mute Rain",
                'color' =>  "#D5CECF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RR 65/023",
                'color' =>  "#D5CECF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 65/051",
                'color' =>  "#D3D0D7",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Violet Morning",
                'color' =>  "#D3D0D6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 64/035",
                'color' =>  "#D3CFD4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 65/042",
                'color' =>  "#D1D1D6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Orchid Smoke",
                'color' =>  "#D1CFD3",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 64/030",
                'color' =>  "#D1CFD3",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 65/049",
                'color' =>  "#D0D1D9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Harmony Touch",
                'color' =>  "#CDC2C4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RR 55/044",
                'color' =>  "#CCC0C0",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Design Time",
                'color' =>  "#C8C1C4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RR 56/029",
                'color' =>  "#C8C1C4",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Misted Lilac",
                'color' =>  "#C4C1C6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 56/036",
                'color' =>  "#C4C1C6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winters Poet",
                'color' =>  "#C2C7D6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Silver Mauve",
                'color' =>  "#BFB6BF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RB 50/062",
                'color' =>  "#BFB6BF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Silver Mauve",
                'color' =>  "#BFB6BF",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Silver Night",
                'color' =>  "#BEB9C5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 50/072",
                'color' =>  "#BEB9C5",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 48/051",
                'color' =>  "#BCB6BD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lady Orchard",
                'color' =>  "#BCB6BD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "City Song",
                'color' =>  "#B8B9C8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 50/086",
                'color' =>  "#B8B9C8",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 49/062",
                'color' =>  "#B8B7C1",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 49/042",
                'color' =>  "#B8B5BC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Little Lilac",
                'color' =>  "#B8B5BC",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cosmic Sea",
                'color' =>  "#B4B3B9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 47/036",
                'color' =>  "#B4B3B9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Misty Autumn",
                'color' =>  "#B4AAAE",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mauve Delight",
                'color' =>  "#B2AFBB",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RR 41/042",
                'color' =>  "#B1A8AD",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Restful Sleep",
                'color' =>  "#A29BA6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 35/067",
                'color' =>  "#A29BA6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 36/055",
                'color' =>  "#A09DA7",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Velvet Glove",
                'color' =>  "#A09DA7",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Evening Peace",
                'color' =>  "#9E919F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RB 31/090",
                'color' =>  "#9E919F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 36/082",
                'color' =>  "#9C9BA9",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 33/103",
                'color' =>  "#9A95A6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Magical Twilight",
                'color' =>  "#9A95A6",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Clay Touch",
                'color' =>  "#9A8B92",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Violet Fantasy",
                'color' =>  "#9693A1",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 32/126",
                'color' =>  "#9194AB",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Joann's Jewel",
                'color' =>  "#9194AB",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Opera House",
                'color' =>  "#8C8B95",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 28/055",
                'color' =>  "#8C8B95",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RR 24/061",
                'color' =>  "#8C7F85",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 26/067",
                'color' =>  "#8A8692",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Rendezvous",
                'color' =>  "#8A8692",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purple Clay",
                'color' =>  "#84747C",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 23/061",
                'color' =>  "#81808B",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lilac Hedge",
                'color' =>  "#81808B",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Plum Paste",
                'color' =>  "#7F7685",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 20/091",
                'color' =>  "#7E7584",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "30RR 19/068",
                'color' =>  "#7E6F75",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Amethyst Reflection",
                'color' =>  "#7D6D7E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70RB 18/117",
                'color' =>  "#7D6D7E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "30RB 16/144",
                'color' =>  "#70677F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Purple Sage",
                'color' =>  "#70677F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Aubergine Swing",
                'color' =>  "#705F68",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pinot Noir",
                'color' =>  "#6F6C81",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 17/122",
                'color' =>  "#6F6C81",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Exotic Stone",
                'color' =>  "#6E718E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Secret Violet",
                'color' =>  "#6C698D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 15/086",
                'color' =>  "#6A6372",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10RR 13/081",
                'color' =>  "#695861",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Pacific Purple",
                'color' =>  "#675F6D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Warehouse District",
                'color' =>  "#675C6D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 13/107",
                'color' =>  "#675C6D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Art Deco",
                'color' =>  "#66656D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 14/049",
                'color' =>  "#66656D",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Fashion Passion",
                'color' =>  "#5A4D70",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 11/133",
                'color' =>  "#595167",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Midnight Glow",
                'color' =>  "#585568",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 09/087",
                'color' =>  "#554C59",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Purple Haze",
                'color' =>  "#55455E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Renaissance Tapestry",
                'color' =>  "#54414C",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RR 08/100",
                'color' =>  "#54414C",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Purple Polka",
                'color' =>  "#534F74",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grape Thistle",
                'color' =>  "#533F4F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10RB 10/116",
                'color' =>  "#524F63",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Grape Cocktail",
                'color' =>  "#514961",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Intense Aubergine",
                'color' =>  "#4E4653",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Calming Clay",
                'color' =>  "#46383E",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RR 06/057",
                'color' =>  "#45383B",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Purple Brooch",
                'color' =>  "#444258",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Blackforest Gateau",
                'color' =>  "#3C3A48",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Black Magic",
                'color' =>  "#3B343F",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "King's Treasure",
                'color' =>  "#343E61",
                'color_group_id' =>  10,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
        ];

        $colorGrp = ColorGroup::where('name', 'Họ màu xanh tím')->first();
        if ($colorGrp) {
            foreach($colors as $cl) {
                $color = Color::create([
                    'name' => $cl['name'],
                    'color' => $cl['color'],
                    'mixed_by_computer' => $cl['mixed_by_computer'],
                    'is_deep_color' => $cl['is_deep_color'],
                    'is_popular' => $cl['is_popular'],
                    'color_group_id' => $colorGrp->id
                ]);
                if ($color) {
                    $color->surfaces()->sync($cl['surfaces']);
                    $color->projecttypes()->sync($cl['projectTypes']);
                }
            }
        }
    }
}
