<?php

use Illuminate\Database\Seeder;
use App\Models\Color;
use App\Models\ColorGroup;
class ColorLemonYellowSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            [
                'name' =>  "Butter Mint",
                'color' =>  "#F7EAB3",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "66YY 83/272",
                'color' =>  "#F7EAB3",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 83/300",
                'color' =>  "#F7E9AD",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "66YY 77/407",
                'color' =>  "#F4E392",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Glimmer",
                'color' =>  "#F4E291",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 79/407",
                'color' =>  "#F4E291",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fern Touch",
                'color' =>  "#F3F2DA",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "84YY 87/135",
                'color' =>  "#F2EDD1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Marvelous Mint",
                'color' =>  "#F1EFCC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "86YY 85/174",
                'color' =>  "#F0EBC7",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Silk Cream",
                'color' =>  "#EFEBD1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Forest Touch",
                'color' =>  "#EEEDD5",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 78/248",
                'color' =>  "#EEE1B0",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Spring Blossom",
                'color' =>  "#EDECCD",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 83/143",
                'color' =>  "#EDECCD",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 83/107",
                'color' =>  "#EDE9D3",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 83/179",
                'color' =>  "#EDE9C5",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Candle Glow",
                'color' =>  "#EDDDA2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 73/288",
                'color' =>  "#EDDDA2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Eggshell Touch",
                'color' =>  "#ECF1E2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cobra Bite",
                'color' =>  "#ECD96A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Spotlight",
                'color' =>  "#ECD461",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "65YY 68/572",
                'color' =>  "#ECD461",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "88YY 81/230",
                'color' =>  "#EBE9BA",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mellow Grasshopper",
                'color' =>  "#EAF0D3",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "New Dew",
                'color' =>  "#EAEBBA",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cardamom Hint",
                'color' =>  "#EAE7C1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tea Paradise",
                'color' =>  "#E8EAD0",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lime Twist",
                'color' =>  "#E8E5AE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "89YY 78/269",
                'color' =>  "#E8E5AE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lemon Grass",
                'color' =>  "#E8E3A8",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "86YY 77/295",
                'color' =>  "#E8E3A8",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sunkissed Lawn",
                'color' =>  "#E8E38C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 66/510",
                'color' =>  "#E8D36D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 83/125",
                'color' =>  "#E7E9CF",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GY 83/064",
                'color' =>  "#E6EADD",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 83/150",
                'color' =>  "#E6EACB",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 78/334",
                'color' =>  "#E6E7A3",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "June Bud",
                'color' =>  "#E6E7A3",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Romaine Lettuce",
                'color' =>  "#E4E184",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Farm Life",
                'color' =>  "#E1DBAE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "88YY 71/380",
                'color' =>  "#E0DD90",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grecian Green",
                'color' =>  "#E0DD90",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Misty Meadows",
                'color' =>  "#DFEBC1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 79/231",
                'color' =>  "#DFE6B7",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 61/561",
                'color' =>  "#DFCB5A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Garden Haven",
                'color' =>  "#DEECAA",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Primavera",
                'color' =>  "#DDDA87",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 69/419",
                'color' =>  "#DDDA87",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 59/485",
                'color' =>  "#D9C869",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "88YY 66/447",
                'color' =>  "#D8D87C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "66YY 56/707",
                'color' =>  "#D8C52B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Spring Creation",
                'color' =>  "#D7DC88",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 74/325",
                'color' =>  "#D6E0A0",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 55/613",
                'color' =>  "#D4C346",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Vertigo",
                'color' =>  "#D2D36F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "89YY 62/494",
                'color' =>  "#D2D36F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 53/638",
                'color' =>  "#CFBF3B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Leaping Lizards",
                'color' =>  "#CFBF3B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 61/504",
                'color' =>  "#CED06A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 52/532",
                'color' =>  "#CEBE53",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Fantasy Garden",
                'color' =>  "#CCC45A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Scorched Grass",
                'color' =>  "#CCBC37",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 48/700",
                'color' =>  "#CBBA1F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "90YY 58/424",
                'color' =>  "#C9CC75",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Limelight",
                'color' =>  "#C9CC75",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 58/424",
                'color' =>  "#C9CC75",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 55/560",
                'color' =>  "#C7CA56",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Lime Jelly",
                'color' =>  "#C6C13B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Magnificent Melon",
                'color' =>  "#C5CF5A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "72YY 47/743",
                'color' =>  "#C3B623",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10GY 61/449",
                'color' =>  "#BDD176",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Parrot Plumage",
                'color' =>  "#BCB928",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "92YY 51/593",
                'color' =>  "#BAC348",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Celery Stalk",
                'color' =>  "#BAC348",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lush Lime",
                'color' =>  "#B9C546",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 48/650",
                'color' =>  "#B9BE35",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "English Apple",
                'color' =>  "#B9BB58",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 48/500",
                'color' =>  "#B9BB58",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70YY 39/613",
                'color' =>  "#B5A728",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70YY 39/613",
                'color' =>  "#B5A728",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Energetic Eden",
                'color' =>  "#B3A236",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mojito Madness",
                'color' =>  "#AFBB34",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Zesty Zucchini",
                'color' =>  "#ACA90C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tennis Lawn",
                'color' =>  "#A4A93A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Midgetgolf Green",
                'color' =>  "#A2CA48",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Natures Soul",
                'color' =>  "#A2AF1D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Palm Sensation",
                'color' =>  "#9A8B30",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Irish Acres",
                'color' =>  "#98B33E",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 41/600",
                'color' =>  "#98B33E",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Otters Dam",
                'color' =>  "#908B2C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 33/525",
                'color' =>  "#8CA23B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Leprechaun Leap",
                'color' =>  "#888C29",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lovely Lime",
                'color' =>  "#86AD3D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sacred Grove",
                'color' =>  "#7D8234",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wicked Witch",
                'color' =>  "#749639",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Glowing Moon",
                'color' =>  "#F6F1DE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "December Moon",
                'color' =>  "#F2E8C9",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 83/150",
                'color' =>  "#F2E8C9",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Eggshell Sheen",
                'color' =>  "#F0F0E0",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "83YY 85/056",
                'color' =>  "#ECEBDC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 83/071",
                'color' =>  "#ECEADA",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 77/207",
                'color' =>  "#ECE1B6",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 77/180",
                'color' =>  "#ECDFBB",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "77YY 83/073",
                'color' =>  "#EBE8D6",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Watery Willow",
                'color' =>  "#E9EAD7",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 83/075",
                'color' =>  "#E8EBDA",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 83/050",
                'color' =>  "#E8E9DC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mountain Mist",
                'color' =>  "#E8E9DC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 72/225",
                'color' =>  "#E8D8AC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Honey Frost",
                'color' =>  "#E8D8AC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 83/100",
                'color' =>  "#E7E7D1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Springwater",
                'color' =>  "#E7E7D1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 75/124",
                'color' =>  "#E6DEC4",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Chardonnay White",
                'color' =>  "#E6DEC4",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 75/120",
                'color' =>  "#E4E1C7",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grashopper",
                'color' =>  "#E2E3D2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Modern Meditation",
                'color' =>  "#E2D8AE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 70/209",
                'color' =>  "#E2D8AE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 72/225",
                'color' =>  "#E1DBAE",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 67/251",
                'color' =>  "#E0D19E",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Khaki Fantasy",
                'color' =>  "#DEDCC1",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Spring Willow",
                'color' =>  "#DED29C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 66/265",
                'color' =>  "#DED29C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 74/087",
                'color' =>  "#DCDECD",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Willow Wood",
                'color' =>  "#DCCE8D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 63/326",
                'color' =>  "#DCCE8D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 71/180",
                'color' =>  "#D9DCB8",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Habitat",
                'color' =>  "#D9D2B8",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 66/130",
                'color' =>  "#D9D2B8",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sea Drops",
                'color' =>  "#D7D4BB",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 67/117",
                'color' =>  "#D7D4BB",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Juicy Pear",
                'color' =>  "#D5D6B5",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 62/264",
                'color' =>  "#D0CD98",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cabbage Patch",
                'color' =>  "#D0CD98",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 59/140",
                'color' =>  "#D0C9AC",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lichen Green",
                'color' =>  "#CDC387",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 55/299",
                'color' =>  "#CDC387",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 50/383",
                'color' =>  "#C9B96D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Shakespeare",
                'color' =>  "#C9B96D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 49/191",
                'color' =>  "#C4B591",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winter's Silence",
                'color' =>  "#C4B591",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 45/382",
                'color' =>  "#C3AF64",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cabbage Crush",
                'color' =>  "#C2C28F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Woodland Mystery",
                'color' =>  "#C1BEA2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 52/138",
                'color' =>  "#C1BEA2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Woodland Mystery",
                'color' =>  "#C1BEA2",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mountain Hike",
                'color' =>  "#BEC198",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 48/255",
                'color' =>  "#BBB786",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 46/160",
                'color' =>  "#B8B192",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Thyme",
                'color' =>  "#B8B192",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 54/238",
                'color' =>  "#B7C292",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Shy Blossom",
                'color' =>  "#B7C292",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Edamame Green",
                'color' =>  "#B7A44B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Chrome Primrose",
                'color' =>  "#B0993F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 34/461",
                'color' =>  "#B0993F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70YY 37/366",
                'color' =>  "#AFA159",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70YY 37/296",
                'color' =>  "#AEA26B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dalmuir Mews",
                'color' =>  "#AEA26B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pine Sensation",
                'color' =>  "#A4A967",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 34/180",
                'color' =>  "#A49B7A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Artichoke Leaf",
                'color' =>  "#A49B7A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Precious Jasper",
                'color' =>  "#A3AC74",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 40/296",
                'color' =>  "#A3AC74",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pacific Pines",
                'color' =>  "#A29F7F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pacific Pines",
                'color' =>  "#A29F7F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 35/169",
                'color' =>  "#A29F7F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 35/304",
                'color' =>  "#A09E64",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Napa Valley",
                'color' =>  "#A09E64",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Carolina",
                'color' =>  "#9F8B33",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 28/443",
                'color' =>  "#9F8B33",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10GY 36/096",
                'color' =>  "#9DA18F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Avocado Salad",
                'color' =>  "#978953",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Hanging Garden",
                'color' =>  "#968A3B",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 30/104",
                'color' =>  "#929480",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 24/438",
                'color' =>  "#91832F",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "90YY 29/464",
                'color' =>  "#8D9138",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Green Lounge",
                'color' =>  "#8D8964",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 19/400",
                'color' =>  "#8D7326",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Highland Dash",
                'color' =>  "#8A8B54",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 21/335",
                'color' =>  "#867B3D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Crested Moss",
                'color' =>  "#867B3D",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 22/200",
                'color' =>  "#817D59",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "90YY 21/371",
                'color' =>  "#7E7F3A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70YY 18/350",
                'color' =>  "#7E7535",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10GY 24/356",
                'color' =>  "#7B8746",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "10GY 21/119",
                'color' =>  "#7A7D67",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Fantastic Foliage",
                'color' =>  "#787336",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Calypso Green",
                'color' =>  "#72813A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 21/375",
                'color' =>  "#72813A",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Tree Love",
                'color' =>  "#6F6845",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 15/279",
                'color' =>  "#6C6B3E",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Ludlow Falls",
                'color' =>  "#6C6B3E",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YY 13/177",
                'color' =>  "#636040",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Plantation Green",
                'color' =>  "#636040",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "70YY 12/167",
                'color' =>  "#615B3C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Camouflage Sensation",
                'color' =>  "#5D5D32",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10GY 12/225",
                'color' =>  "#596138",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Hawthorne Green",
                'color' =>  "#53594C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GY 11/076",
                'color' =>  "#53594C",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
            [
                'name' =>  "Deep Waters",
                'color' =>  "#465439",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GY 09/171",
                'color' =>  "#465439",
                'color_group_id' =>  6,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [
        ],
            ],
        ];

        $colorGrp = ColorGroup::where('name', 'Họ màu vàng chanh')->first();
        if ($colorGrp) {
            foreach($colors as $cl) {
                $color = Color::create([
                    'name' => $cl['name'],
                    'color' => $cl['color'],
                    'mixed_by_computer' => $cl['mixed_by_computer'],
                    'is_deep_color' => $cl['is_deep_color'],
                    'is_popular' => $cl['is_popular'],
                    'color_group_id' => $colorGrp->id
                ]);
                if ($color) {
                    $color->surfaces()->sync($cl['surfaces']);
                    $color->projecttypes()->sync($cl['projectTypes']);
                }
            }
        }
    }
}
