<?php

use Illuminate\Database\Seeder;
use App\Models\Color;
use App\Models\ColorGroup;
class ColorWhiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            [
                'name' =>  "Vanilla Sensation",
                'color' =>  "#F7F0DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Ivory Sparkle",
                'color' =>  "#F7EBDC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Polar Heights",
                'color' =>  "#F6F2E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Chantilly Cream",
                'color' =>  "#F6EBD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Tutu",
                'color' =>  "#F5EFE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Marshmallow Touch",
                'color' =>  "#F5EEE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "42YY 87/084",
                'color' =>  "#F5EBD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Arizona White",
                'color' =>  "#F5EBD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "61YY 89/040",
                'color' =>  "#F4F0E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Ophelia",
                'color' =>  "#F4E9D7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 83/086",
                'color' =>  "#F4E9D7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Ivory Fantasy",
                'color' =>  "#F4E9D6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Purest Frost",
                'color' =>  "#F3F2EC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Linen Lush",
                'color' =>  "#F3EDDD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Emily's Expression",
                'color' =>  "#F3E8D4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 83/094",
                'color' =>  "#F3E8D4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cotton Fantasy",
                'color' =>  "#F2F1E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Brave Baby",
                'color' =>  "#F2EFE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wedding Capel",
                'color' =>  "#F2EDE3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fluffy Clouds",
                'color' =>  "#F2ECE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Wallwash",
                'color' =>  "#F2ECE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "53YY 87/070",
                'color' =>  "#F2EAD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "20YY 83/075",
                'color' =>  "#F2E8D9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wonderland White",
                'color' =>  "#F1F1ED",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Clinic White",
                'color' =>  "#F1F0E8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "61YY 85/050",
                'color' =>  "#F1EDE0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "03YY 86/021",
                'color' =>  "#F1ECE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 83/064",
                'color' =>  "#F1E9DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "80YR 83/044",
                'color' =>  "#F1E8E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "29YY 84/067",
                'color' =>  "#F1E8DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 83/086",
                'color' =>  "#F1E8D4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Neutral Garden",
                'color' =>  "#F1E7D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Frosty Feeling",
                'color' =>  "#F0EEE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "81YY 87/031",
                'color' =>  "#F0EEE3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cotton Breeze",
                'color' =>  "#F0EDE4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "66YY 85/045",
                'color' =>  "#F0EDE2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YR 83/034",
                'color' =>  "#F0E8E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Whitney White",
                'color' =>  "#F0E8E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Captured Light",
                'color' =>  "#F0E7E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YR 83/034",
                'color' =>  "#F0E7E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "88YR 82/046",
                'color' =>  "#F0E5DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "82YY 85/038",
                'color' =>  "#EFEDE2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10YY 83/029",
                'color' =>  "#EFE9E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Faux Naturale",
                'color' =>  "#EFE9E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 83/043",
                'color' =>  "#EFE9DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "20YY 83/050",
                'color' =>  "#EFE8DD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 83/057",
                'color' =>  "#EFE8DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mystic Mist",
                'color' =>  "#EFE8D9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "00YY 83/046",
                'color' =>  "#EFE5DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Enlightened Peach",
                'color' =>  "#EFE5DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Delaney's Blossom",
                'color' =>  "#EFE4DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "00YY 83/057",
                'color' =>  "#EFE4DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White On White",
                'color' =>  "#EEEFEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GY 88/014",
                'color' =>  "#EEEFEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Elegant Cotton",
                'color' =>  "#EEEFE8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "44YY 84/042",
                'color' =>  "#EEE9DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Whisper",
                'color' =>  "#EEE9DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YR 83/035",
                'color' =>  "#EEE7DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YR 83/025",
                'color' =>  "#EEE6E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Inner Peace",
                'color' =>  "#EEE6E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90RB 83/015",
                'color' =>  "#EDEAEB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Summer Wedding",
                'color' =>  "#EDEAEB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Soft Shimmer",
                'color' =>  "#EDE8E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YR 83/020",
                'color' =>  "#EDE8E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "20YY 83/025",
                'color' =>  "#EDE8E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Egret",
                'color' =>  "#EDE8DD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "39YY 85/046",
                'color' =>  "#EDE8DD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tusk Tusk",
                'color' =>  "#EDE3D5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 79/070",
                'color' =>  "#EDE3D5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Dewdrop Grey",
                'color' =>  "#ECEDE7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YR 83/018",
                'color' =>  "#ECE9E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YY 83/037",
                'color' =>  "#ECE9E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YY 83/062",
                'color' =>  "#ECE6D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Natural Sensation",
                'color' =>  "#ECE2D1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Smokey Hint",
                'color' =>  "#EBEAE8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Natural White",
                'color' =>  "#EBE7DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YY 83/029",
                'color' =>  "#EBE7DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cielo Blanco",
                'color' =>  "#EBE6DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "43YY 81/051",
                'color' =>  "#EBE6DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mindblowing Morning",
                'color' =>  "#EAE4DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 79/053",
                'color' =>  "#EAE3D7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Opal",
                'color' =>  "#EAE3D7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Remain Neutral",
                'color' =>  "#EAE0CD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "39YY 77/091",
                'color' =>  "#EAE0CD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Crystal",
                'color' =>  "#E9EAE9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50BG 83/009",
                'color' =>  "#E9EAE9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Moonlight Sonata",
                'color' =>  "#E9E9E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BB 83/013",
                'color' =>  "#E9E9E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Magnolia Springs",
                'color' =>  "#E9E9E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50BB 83/006",
                'color' =>  "#E9E9E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RB 83/005",
                'color' =>  "#E9E7E6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Drifting Snow",
                'color' =>  "#E8EAE9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BB 83/014",
                'color' =>  "#E8EAE9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Cube",
                'color' =>  "#E8E3DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Natural Yoghurt",
                'color' =>  "#E7E4D9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "City Sensation",
                'color' =>  "#E6E7E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "45YY 83/062",
                'color' =>  "#F0E8DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Stowe White",
                'color' =>  "#F0E8DA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YR 83/026",
                'color' =>  "#EFE8E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Angel Hair",
                'color' =>  "#EFE8E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "20YY 83/038",
                'color' =>  "#EFE8DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Calm Winds",
                'color' =>  "#EFE7E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "80YR 83/035",
                'color' =>  "#EFE7E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Mellow Snow",
                'color' =>  "#EEEDE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Cuddle",
                'color' =>  "#EEE7E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "80YR 83/026",
                'color' =>  "#EEE7E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Secret Affair",
                'color' =>  "#EDE8E3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "60YR 83/017",
                'color' =>  "#EDE8E3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "80YR 83/017",
                'color' =>  "#EDE8E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Tranquil Mist",
                'color' =>  "#EDE8DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70YR 83/026",
                'color' =>  "#EDE7E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sand Dollar Shell",
                'color' =>  "#EDE7E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "51YY 83/060",
                'color' =>  "#EDE6D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pacific Mist",
                'color' =>  "#EDE6D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "55YR 83/024",
                'color' =>  "#EDE4DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Teacup",
                'color' =>  "#EDE4DE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Fresh Air",
                'color' =>  "#ECEAED",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 83/012",
                'color' =>  "#ECEAE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 8,],
            ],
            [
                'name' =>  "Cloudy Sunday",
                'color' =>  "#ECE9E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wedding White",
                'color' =>  "#ECE9E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90RR 83/009",
                'color' =>  "#ECE8E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10YY 83/014",
                'color' =>  "#EBE8E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 83/021",
                'color' =>  "#EBE8E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "43YY 78/053",
                'color' =>  "#EBE5D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winterwash",
                'color' =>  "#EAE8E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Sheer Sensation",
                'color' =>  "#EAE8E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YR 83/003",
                'color' =>  "#EAE8E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YR 83/010",
                'color' =>  "#EAE8E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50YR 83/015",
                'color' =>  "#EAE6E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Baby Girl",
                'color' =>  "#EAE6E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Baby Girl",
                'color' =>  "#EAE6E1",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GY 83/010",
                'color' =>  "#E9EAE5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Simple",
                'color' =>  "#E9E8E8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Penguin Walk",
                'color' =>  "#E9E8E8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 83/011",
                'color' =>  "#E9E8E8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pearl Drop",
                'color' =>  "#E8EAEB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Atmosphere",
                'color' =>  "#E8EAE9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GG 83/006",
                'color' =>  "#E8E9E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Crystal Glimmer",
                'color' =>  "#E8E8EB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Song Porcelain",
                'color' =>  "#E8E8E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "00NN 83/000",
                'color' =>  "#E8E8E5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Silk Moon",
                'color' =>  "#E8E8E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BB 83/001",
                'color' =>  "#E8E8E4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "81YY 81/016",
                'color' =>  "#E8E7E3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Quiet Hideaway",
                'color' =>  "#E8E7E3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Precious Paper",
                'color' =>  "#E8E4E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "98YR 78/041",
                'color' =>  "#E8E0D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 75/084",
                'color' =>  "#E8DECE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GG 83/013",
                'color' =>  "#E7EAE8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GG 83/011",
                'color' =>  "#E7EAE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winter's Day",
                'color' =>  "#E7EAE6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Energetic Mirage",
                'color' =>  "#E7E0D3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BB 83/020",
                'color' =>  "#E6EAEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10BB 83/017",
                'color' =>  "#E6E9E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Nova White",
                'color' =>  "#E6E9E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90GG 83/011",
                'color' =>  "#E6E9E6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Snowed In",
                'color' =>  "#E6E9E6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Snowed In",
                'color' =>  "#E6E9E6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Kitten White",
                'color' =>  "#E6E1D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 78/035",
                'color' =>  "#E6E1D8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Wisdom",
                'color' =>  "#E5E0DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Wash Out",
                'color' =>  "#E5DFD7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Barcelona Rain",
                'color' =>  "#E4E7E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "59BB 81/022",
                'color' =>  "#E4E7E9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 78/018",
                'color' =>  "#E4E1DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winter Bird",
                'color' =>  "#E4E1DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winter Bird",
                'color' =>  "#E4E1DB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Woodwind",
                'color' =>  "#E4DBD0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "20YY 74/055",
                'color' =>  "#E4DBD0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "40YY 74/056",
                'color' =>  "#E3DDD2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10YY 73/042",
                'color' =>  "#E3DCD4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Autumnal Equinox",
                'color' =>  "#E3DCD4",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Chilly Morning",
                'color' =>  "#E2E7E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "56BG 81/023",
                'color' =>  "#E2E7E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Velvet Rain",
                'color' =>  "#E2E5E6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Winters Walk",
                'color' =>  "#E1E2DD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GY 76/017",
                'color' =>  "#E0E1DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "N.b.c. White",
                'color' =>  "#E0E1DC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Heatherbelle",
                'color' =>  "#E0DAD5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Heatherbelle",
                'color' =>  "#E0DAD5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90YR 73/029",
                'color' =>  "#E0DAD5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Lavender Touch",
                'color' =>  "#DFE2E7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "10YY 72/021",
                'color' =>  "#DFDAD5",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "City Skyline",
                'color' =>  "#DEE2E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Resting Seagul",
                'color' =>  "#DEDEDA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 72/018",
                'color' =>  "#DEDCD7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Pelican",
                'color' =>  "#DEDCD7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "09BB 77/019",
                'color' =>  "#DDE2E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30YY 72/009",
                'color' =>  "#DDDCD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Rabbit",
                'color' =>  "#DDDAD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50RR 72/010",
                'color' =>  "#DDDAD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 73/027",
                'color' =>  "#DCDCE0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Ice Ballet",
                'color' =>  "#DCDBDB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30RB 73/016",
                'color' =>  "#DCDBDB",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70BB 73/030",
                'color' =>  "#DBDDE0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Star-crossed",
                'color' =>  "#DBDDE0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70BB 74/040",
                'color' =>  "#DBDCE2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50BG 72/006",
                'color' =>  "#DBDCDA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Arctic Char",
                'color' =>  "#DBDBDD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "90BB 73/022",
                'color' =>  "#DBDBDD",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Groovy Grey",
                'color' =>  "#DAE0E2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "70BB 73/020",
                'color' =>  "#DADBDC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "White Wisteria",
                'color' =>  "#DADBDC",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "50GY 72/012",
                'color' =>  "#DADBD6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "The Plaza",
                'color' =>  "#DADBD6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Touch Of Grey",
                'color' =>  "#DADAD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30BB 72/003",
                'color' =>  "#DADAD9",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Grey Clouds",
                'color' =>  "#D9DAD8",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "00NN 72/000",
                'color' =>  "#D8D8D7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  1,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Snowfield",
                'color' =>  "#D8D8D7",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "Shaded Ice",
                'color' =>  "#D7D9D6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "30GG 72/008",
                'color' =>  "#D7D9D6",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  1,
                'is_popular' =>  0,
                'is_deep_color' =>  1,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "76824",
                'color' =>  "#F7E9D2",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "25155",
                'color' =>  "#F6F7F3",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "76925",
                'color' =>  "#F0EBDE",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "74380",
                'color' =>  "#E8E9DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "21312",
                'color' =>  "#E6EAEA",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 1, 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "76245",
                'color' =>  "#DFE5DF",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
            [
                'name' =>  "71560",
                'color' =>  "#DEE0E0",
                'color_group_id' =>  1,
                'mixed_by_computer' =>  0,
                'is_popular' =>  0,
                'is_deep_color' =>  0,
                'surfaces' => [ 2,],
                'projectTypes' => [ 1, 2, 3, 4, 5, 6, 7, 8,],
            ],
        ];

        $whiteColorGrp = ColorGroup::where('name', 'Họ màu trắng')->first();
        if ($whiteColorGrp) {
            foreach($colors as $cl) {
                $color = Color::create([
                    'name' => $cl['name'],
                    'color' => $cl['color'],
                    'mixed_by_computer' => $cl['mixed_by_computer'],
                    'is_deep_color' => $cl['is_deep_color'],
                    'is_popular' => $cl['is_popular'],
                    'color_group_id' => $whiteColorGrp->id
                ]);
                if ($color) {
                    $color->surfaces()->sync($cl['surfaces']);
                    $color->projecttypes()->sync($cl['projectTypes']);
                }
            }
        }
    }
}
