<script type="text/javascript" src="{{asset('js/frontend/advagg_js1.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js2.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js3.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js4.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js5.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js6.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js7.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js8.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js9.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js10.js') }}"></script>
<script type="text/javascript" src="{{asset('js/frontend/advagg_js11.js') }}"></script>
